### ISSUE TITLE
禁止 sponsor 注册

### ISSUE THREAD

**Issue by liushooter** [SolDevCn/earn#15]
隐藏 sponsor的 页面、 api登录方式

如果有人想注册为sponsor，页面显示为 “向管理员发送邮件或者IM，开通相应权限”

**Comment by Morboz** [comment]
目前考虑实现方式：
1. 注册sponsor的页面在/new/sponsor，当前用户角色非GOD时，不显示表单，仅展示文字提示。
2. 表单后台接口是/api/sponsors/create， 当调用这个接口的角色非GOD时，返回403错误。

另外，用户需要知道管理员的邮件地址，页面需要展示出管理员邮件地址。
如何获取管理员的邮件地址，目前想到通过环境变量，新增一个NEXT_PUBLIC_EARN_GOD_EMAIL的环境变量

同样新增tg的联系方式的配置NEXT_PUBLIC_EARN_GOD_TELEGRAM

**Comment by liushooter** [comment]
https://github.com/SolDevCn/earn/pull/17 done
