### ISSUE TITLE
翻译问题汇总

### ISSUE THREAD

**Issue by liushooter** [SolDevCn/earn#23]
请参考 https://github.com/SolDevCn/earn/issues/22

**Comment by Chainguys** [comment]
<img width="1389" alt="p0" src="https://github.com/user-attachments/assets/7f5a717e-9186-489b-a26c-ddfa59161692">
先打个样 看看这样标注和贴图你们觉得清晰吗 阅读起来舒服吗 争取三张图之内做到信息流明确 阅读体验好

**Comment by Chainguys** [comment]
<img width="1409" alt="p1" src="https://github.com/user-attachments/assets/8898d234-5bc7-4ea4-be43-e728a0e0525c">

红圈text修改为 "一站式自助申请Solana生态最好公司的悬赏、项目
和资助。"

**Comment by Chainguys** [comment]
<img width="1394" alt="p2" src="https://github.com/user-attachments/assets/ea980ecb-e582-48b3-9f87-8f5ac325177d">
对 公共组件 已经提出过的问题就不再专门提了

**Comment by Chainguys** [comment]
<img width="1392" alt="p3" src="https://github.com/user-attachments/assets/7083cb26-e8bd-4ec6-82a2-33c4a0ed3f2e">

**Comment by Chainguys** [comment]
<img width="1392" alt="p4" src="https://github.com/user-attachments/assets/cea3bb6a-5d9b-4ee2-9231-b0b895585db2">

**Comment by Chainguys** [comment]
<img width="1367" alt="p3-1" src="https://github.com/user-attachments/assets/cfeb5276-6b49-4a79-8085-1038713577bd">

**Comment by Chainguys** [comment]
<img width="1403" alt="p5" src="https://github.com/user-attachments/assets/6f52d41a-afba-4c44-af3e-26e0811d6e91">

**Comment by Chainguys** [comment]
<img width="1361" alt="p6" src="https://github.com/user-attachments/assets/ed714123-5303-40ca-8804-cdd161d4680e">

**Comment by Chainguys** [comment]
"需要资金来构建您的梦想？
发掘可能支持您项目的所有可用资助
快捷 非股权 无套路"
<img width="1137" alt="p7" src="https://github.com/user-attachments/assets/eccc7721-eeec-4a62-8113-28760346a732">

**Comment by Chainguys** [comment]
<img width="1263" alt="p8" src="https://github.com/user-attachments/assets/40fbb450-1e38-469b-8958-03575b3c64e6">

**Comment by Chainguys** [comment]
<img width="1307" alt="p9" src="https://github.com/user-attachments/assets/389b057a-bb31-44f4-9cc2-30b700dc3a47">

**Comment by Chainguys** [comment]
<img width="1163" alt="p10" src="https://github.com/user-attachments/assets/1af18a05-6e9a-4b68-9ea0-bc8dfe2b45a5">

**Comment by Chainguys** [comment]
<img width="1212" alt="p11" src="https://github.com/user-attachments/assets/d4eed35e-9621-4814-9bf6-d47a3465d282">
<img width="1141" alt="p12" src="https://github.com/user-attachments/assets/065fb81a-718c-4b22-8621-4d941813b6de">
<img width="1285" alt="p13" src="https://github.com/user-attachments/assets/b22a8e9c-1e5a-4ad7-a2db-a1d685862ce0">

**Comment by Chainguys** [comment]
<img width="360" alt="p14" src="https://github.com/user-attachments/assets/da61ada5-d31e-45ed-ad7d-565eeb8a987a">
<img width="805" alt="p15" src="https://github.com/user-attachments/assets/00df6d15-efdd-45e3-8f55-44c5e083be65">
<img width="727" alt="p16" src="https://github.com/user-attachments/assets/d01c0d80-8a64-4043-b7fa-f21f381a7dd4">
<img width="899" alt="p17" src="https://github.com/user-attachments/assets/2496636d-389e-4d04-8720-d1664965a771">

**Comment by Chainguys** [comment]
<img width="1003" alt="p18" src="https://github.com/user-attachments/assets/7cfeb854-84a6-4088-9735-252dc488d619">

**Comment by cryptosheep1** [comment]
https://drive.google.com/file/d/1FM1jL4HUaoXHiafhXuiuA6MJvMb9estw/view?usp=sharing
[Solar Earn发布任务做任务前翻译.pdf](https://github.com/user-attachments/files/17610969/Solar.Earn.pdf)
[Solar Earn发布任务做任务前翻译.pptx](https://github.com/user-attachments/files/17610970/Solar.Earn.pptx)

**Comment by cryptosheep1** [comment]
[Solar Earn新域名翻译.pdf](https://github.com/user-attachments/files/17772194/Solar.Earn.pdf)
[Solar Earn新域名翻译.pptx](https://github.com/user-attachments/files/17772196/Solar.Earn.pptx)
