### ISSUE TITLE
添加 Admin panel——超级管理员

### ISSUE THREAD

**Issue by liushooter** [SolDevCn/earn#3]
https://github.com/premieroctet/next-admin

or

https://dev.to/nikpoltoratsky/how-to-create-an-admin-panel-for-your-postgresql-database-on-railway-cloud-1gib

**Comment by liushooter** [comment]
/admin/usersponsors/ 500
/admin/user/0e5835dc-c3fd-432f-8ac7-9857548f147e/ 500

**Comment by Morboz** [comment]
由于47.250.177.135连接数据库的Grants表缺少isPrivate字段。
![image](https://github.com/user-attachments/assets/b36a1e9d-1e01-4b30-8a03-e7387957f925)

alter grants table 添加isPrivate字段后不再500
