### ISSUE TITLE
sponsor  状态

### ISSUE THREAD

**Issue by liushooter** [SolDevCn/earn#4]
sponsor可以注册后， 需要super admin验证后，才能正常使用

**Comment by Morboz** [comment]
user cases:
1. 普通用户正常注册sponsor后，isActive字段标记为false，当god通过dashboard页面激活之后，才将isActive变为true
2. 普通sponsor当isActive为false的时候，无法正常使用/dashboard页面，页面展示“联系管理员获得权限” 
![image](https://github.com/user-attachments/assets/af720627-2787-4ac6-8ce1-64c1fa1a5050)
3. god在浏览dashboard页面，如果sponsor未激活，在create listing按钮上加一个 activate sponsor的按钮，如果已激活就显示activated或者不显示按钮
